server:
  port: 8003

spring:
  application:
    name: server_courses
  profiles:
    active: dev

  #Configuration of MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/grainacademy
    username: root
    password: 05190602Fc@

  #Timezone of the DataTime in the returning JSON
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #DateTime display format
    time-zone: GMT+8 #Chinese TimeZone

#Configuration of MyBatis Plus
mybatis-plus:
  global-config:
    #Enable logical deletion
    db-config:
      logic-delete-field: deleted #全局逻辑删除字段名
      logic-delete-value: 1 #删除逻辑值
      logic-not-delete-value: 0 #未删除逻辑值

#Configuration for springdoc-openapi
springdoc:
  swagger-ui:
    #springdoc access address
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      #需要扫描的包,这里需要改成你自己的.
      packages-to-scan: com.grainacademy.backend

#A UI Booster for Swagger
knife4j:
  enable: true
  setting:
    language: zh_cn